// src/components/ai/PartyUpdater.tsx

import { useState, useEffect } from 'react';
import { useToast } from "@/components/ui/use-toast";
import { Button } from "@/components/ui/button";
import { checkAndUpdateParties, updatePartiesWithAI, PartyUpdateInfo } from "@/utils/aiPartyUpdater";
import { RefreshCw } from "lucide-react";

export const PartyUpdater = () => {
  const { toast } = useToast();
  const [lastUpdate, setLastUpdate] = useState<PartyUpdateInfo>({
    lastUpdated: "never",
    changedClubs: []
  });
  const [isUpdating, setIsUpdating] = useState(false);

  // Check for updates when the component mounts
  useEffect(() => {
    const updateInfo = checkAndUpdateParties();
    setLastUpdate(updateInfo);
  }, []);

  const handleManualUpdate = () => {
    setIsUpdating(true);
    
    // Simulate a delay for the AI processing
    setTimeout(() => {
      const updateInfo = updatePartiesWithAI();
      setLastUpdate(updateInfo);
      
      // Show toast with results
      if (updateInfo.changedClubs.length > 0) {
        toast({
          title: "Party Updates!",
          description: `${updateInfo.changedClubs.length} clubs have updated their party status.`,
          duration: 5000,
        });
      } else {
        toast({
          title: "No Changes",
          description: "Our AI didn't find any clubs to update today.",
          duration: 3000,
        });
      }
      
      setIsUpdating(false);
      
      // Trigger page reload to update the map and club lists
      window.location.reload();
    }, 1500);
  };

  return (
    <div className="flex items-center gap-2 p-2 text-sm bg-background/80 backdrop-blur-sm rounded-lg border border-muted">
      <div className="flex flex-col">
        <span className="font-medium">AI Party Updates</span>
        <span className="text-xs text-muted-foreground">
          Last updated: {lastUpdate.lastUpdated === "never" ? "Never" : new Date(lastUpdate.lastUpdated).toLocaleDateString()}
        </span>
      </div>
      <Button 
        variant="outline" 
        size="sm" 
        onClick={handleManualUpdate} 
        disabled={isUpdating}
      >
        {isUpdating ? (
          <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
        ) : (
          <RefreshCw className="h-4 w-4 mr-2" />
        )}
        {isUpdating ? "Updating..." : "Update Now"}
      </Button>
    </div>
  );
};

export default PartyUpdater;

// angular-migration/components/party-updater/party-updater.component.ts

import { Component, OnInit } from '@angular/core';
import { PartyUpdaterService, PartyUpdateInfo } from '../../services/party-updater.service';

@Component({
  selector: 'app-party-updater',
  templateUrl: './party-updater.component.html',
  styleUrls: ['./party-updater.component.scss']
})
export class PartyUpdaterComponent implements OnInit {
  lastUpdate: PartyUpdateInfo = {
    lastUpdated: "never",
    changedClubs: []
  };
  isUpdating = false;
  
  constructor(
    private partyUpdaterService: PartyUpdaterService,
    private toastService: ToastService // You would create this service for Angular
  ) {}
  
  ngOnInit(): void {
    const updateInfo = this.partyUpdaterService.checkAndUpdateParties();
    this.lastUpdate = updateInfo;
  }
  
  handleManualUpdate(): void {
    this.isUpdating = true;
    
    // Simulate a delay for the AI processing
    setTimeout(() => {
      const updateInfo = this.partyUpdaterService.updatePartiesWithAI();
      this.lastUpdate = updateInfo;
      
      // Show toast with results
      if (updateInfo.changedClubs.length > 0) {
        this.toastService.show({
          title: "Party Updates!",
          description: `${updateInfo.changedClubs.length} clubs have updated their party status.`,
          duration: 5000,
        });
      } else {
        this.toastService.show({
          title: "No Changes",
          description: "Our AI didn't find any clubs to update today.",
          duration: 3000,
        });
      }
      
      this.isUpdating = false;
      
      // Trigger page reload to update the map and club lists
      window.location.reload();
    }, 1500);
  }
}


<div class="flex items-center gap-2 p-2 text-sm bg-background/80 backdrop-blur-sm rounded-lg border border-muted">
  <div class="flex flex-col">
    <span class="font-medium">AI Party Updates</span>
    <span class="text-xs text-muted-foreground">
      Last updated: {{ lastUpdate.lastUpdated === "never" ? "Never" : (lastUpdate.lastUpdated | date) }}
    </span>
  </div>
  <button 
    class="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-9 px-3"
    [disabled]="isUpdating"
    (click)="handleManualUpdate()"
  >
    <svg *ngIf="isUpdating" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4 mr-2 animate-spin">
      <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"></path>
      <path d="M21 3v5h-5"></path>
      <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"></path>
      <path d="M3 21v-5h5"></path>
    </svg>
    <svg *ngIf="!isUpdating" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4 mr-2">
      <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"></path>
      <path d="M21 3v5h-5"></path>
      <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"></path>
      <path d="M3 21v-5h5"></path>
    </svg>
    {{ isUpdating ? "Updating..." : "Update Now" }}
  </button>
</div>
