// src/components/clubs/CarouselClubList.tsx

import { Club } from "@/data/clubData";
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from "@/components/ui/carousel";
import FeaturedClubCard from "./FeaturedClubCard";
import { useCarouselState } from "@/hooks/useCarouselState";

interface CarouselClubListProps {
  title: string;
  clubs: Club[];
}

const CarouselClubList = ({ title, clubs }: CarouselClubListProps) => {
  const { currentIndex, api, setApi } = useCarouselState();

  if (clubs.length === 0) {
    return null;
  }

  return (
    <div className="space-y-3">
      <div className="flex items-baseline gap-2">
        <h2 className="text-2xl font-bold text-foreground">{title}</h2>
        <span className="text-sm text-muted-foreground">Featured</span>
      </div>
      
      <div className="w-full relative">
        <Carousel
          className="w-full"
          opts={{
            align: "start",
            loop: true,
          }}
          setApi={setApi}
        >
          <CarouselContent>
            {clubs.map((club) => (
              <CarouselItem key={club.id}>
                <FeaturedClubCard club={club} />
              </CarouselItem>
            ))}
          </CarouselContent>
          
          <div className="absolute -right-4 top-1/2 -translate-y-1/2 z-10">
            <CarouselNext className="h-12 w-12 rounded-full bg-party text-white border-none shadow-lg hover:bg-party-dark" />
          </div>
          <div className="absolute -left-4 top-1/2 -translate-y-1/2 z-10">
            <CarouselPrevious className="h-12 w-12 rounded-full bg-party text-white border-none shadow-lg hover:bg-party-dark" />
          </div>
        </Carousel>
        
        <div className="flex justify-center gap-1 mt-4">
          {clubs.map((_, index) => (
            <div
              key={index}
              className={`h-1.5 rounded-full transition-all ${
                currentIndex === index ? "w-8 bg-party" : "w-3 bg-muted"
              }`}
            />
          ))}
        </div>
      </div>
    </div>
  );
};

export default CarouselClubList;

// angular-migration/components/carousel-club-list/carousel-club-list.component.ts

import { Component, Input, OnInit } from '@angular/core';
import { Club } from '../../models/club.model';

@Component({
  selector: 'app-carousel-club-list',
  templateUrl: './carousel-club-list.component.html',
  styleUrls: ['./carousel-club-list.component.scss']
})
export class CarouselClubListComponent implements OnInit {
  @Input() title: string = '';
  @Input() clubs: Club[] = [];
  
  currentIndex = 0;
  
  constructor() {}
  
  ngOnInit(): void {}
  
  setCurrentIndex(index: number): void {
    this.currentIndex = index;
  }
  
  nextSlide(): void {
    this.currentIndex = (this.currentIndex + 1) % this.clubs.length;
  }
  
  previousSlide(): void {
    this.currentIndex = (this.currentIndex - 1 + this.clubs.length) % this.clubs.length;
  }
}


<div *ngIf="clubs.length > 0" class="space-y-3">
  <div class="flex items-baseline gap-2">
    <h2 class="text-2xl font-bold text-foreground">{{title}}</h2>
    <span class="text-sm text-muted-foreground">Featured</span>
  </div>
  
  <div class="w-full relative">
    <!-- In a real implementation, you'd use an Angular carousel library like ngx-owl-carousel-o -->
    <div class="carousel">
      <div class="carousel-content" [style.transform]="'translateX(-' + (currentIndex * 100) + '%)'">
        <div *ngFor="let club of clubs" class="carousel-item">
          <app-featured-club-card [club]="club"></app-featured-club-card>
        </div>
      </div>
      
      <button class="absolute -right-4 top-1/2 -translate-y-1/2 z-10 h-12 w-12 rounded-full bg-party text-white border-none shadow-lg hover:bg-party-dark flex items-center justify-center"
              (click)="nextSlide()">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="m9 18 6-6-6-6"/>
        </svg>
      </button>
      <button class="absolute -left-4 top-1/2 -translate-y-1/2 z-10 h-12 w-12 rounded-full bg-party text-white border-none shadow-lg hover:bg-party-dark flex items-center justify-center"
              (click)="previousSlide()">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="m15 18-6-6 6-6"/>
        </svg>
      </button>
    </div>
    
    <div class="flex justify-center gap-1 mt-4">
      <div *ngFor="let club of clubs; let i = index"
           class="h-1.5 rounded-full transition-all"
           [ngClass]="currentIndex === i ? 'w-8 bg-party' : 'w-3 bg-muted'">
      </div>
    </div>
  </div>
</div>
