// src/components/clubs/FeaturedClubCard.tsx

import { useState, useEffect } from "react";
import { Club, addToFavorites, removeFromFavorites, isFavorite } from "@/data/clubData";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Music, MapPin, Star, Clock, ArrowRight, Heart, Ticket } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import ClubDetailsDialog from "./ClubDetailsDialog";

interface FeaturedClubCardProps {
  club: Club;
}

const FeaturedClubCard = ({ club }: FeaturedClubCardProps) => {
  const { toast } = useToast();
  const [favorited, setFavorited] = useState(false);
  const [detailsOpen, setDetailsOpen] = useState(false);
  
  useEffect(() => {
    setFavorited(isFavorite(club.id));
  }, [club.id]);

  const handleFavoriteToggle = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (favorited) {
      removeFromFavorites(club.id);
      setFavorited(false);
      toast({
        title: "Removed from favorites",
        description: `${club.name} has been removed from your favorites`,
      });
    } else {
      addToFavorites(club.id);
      setFavorited(true);
      toast({
        title: "Added to favorites",
        description: `${club.name} has been added to your favorites`,
      });
    }
  };

  return (
    <>
      <Card 
        className="w-full border-0 overflow-hidden group transition-all duration-300 relative cursor-pointer" 
        onClick={() => setDetailsOpen(true)}
      >
        {club.image && (
          <div className="w-full h-[300px] overflow-hidden relative">
            <div className="absolute inset-0 bg-gradient-to-t from-background to-transparent z-10" />
            <img 
              src={club.image} 
              alt={club.name} 
              className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
            />
            <div className="absolute top-4 right-4 z-20">
              <Button 
                variant="outline" 
                size="icon" 
                className={`rounded-full ${favorited ? 'bg-red-500 text-white border-none' : 'bg-background/30 backdrop-blur-sm'}`}
                onClick={handleFavoriteToggle}
              >
                <Heart className={`h-5 w-5 ${favorited ? 'fill-current' : ''}`} />
              </Button>
            </div>
            <div className="absolute bottom-0 left-0 right-0 p-6 z-20">
              <h2 className="text-2xl font-bold mb-2">{club.name}</h2>
              
              <div className="flex items-center gap-2 mb-3">
                <Badge variant="outline" className="bg-background/30 backdrop-blur-sm">
                  <Star className="h-3 w-3 text-yellow-500 mr-1" /> {club.rating}
                </Badge>
                <Badge variant="outline" className="bg-background/30 backdrop-blur-sm">
                  <Clock className="h-3 w-3 mr-1" /> {club.openingHours}
                </Badge>
                {club.activeParty && (
                  <Badge className="bg-party">
                    <Music className="h-3 w-3 mr-1" /> Active Party
                  </Badge>
                )}
              </div>
              
              <p className="text-sm text-muted-foreground mb-4 max-w-2xl line-clamp-2">
                {club.description}
              </p>
              
              <div className="space-y-2">
                <div>
                  <h3 className="text-sm font-medium uppercase text-muted-foreground mb-1">
                    Featured Artist
                  </h3>
                  <p className="text-lg">
                    Artist
                  </p>
                </div>
                
                <div>
                  <h3 className="text-sm font-medium uppercase text-muted-foreground mb-1">
                    Location
                  </h3>
                  <p className="text-sm flex items-center">
                    <MapPin className="h-4 w-4 mr-1" /> {club.address}
                  </p>
                </div>
                
                <div className="flex flex-wrap gap-1 mt-3">
                  {club.musicGenres.map((genre) => (
                    <Badge key={genre} variant="secondary" className="text-xs">
                      {genre}
                    </Badge>
                  ))}
                </div>
              </div>
              
              <div className="flex flex-wrap gap-2 mt-4">
                <Button className="party-button">
                  Learn More <ArrowRight className="h-4 w-4 ml-1" />
                </Button>
                <Button variant="outline" className="bg-background/30 backdrop-blur-sm" onClick={() => setDetailsOpen(true)}>
                  <Ticket className="h-4 w-4 mr-1" /> Buy Tickets
                </Button>
              </div>
            </div>
          </div>
        )}
      </Card>

      <ClubDetailsDialog
        club={club}
        open={detailsOpen}
        onOpenChange={setDetailsOpen}
      />
    </>
  );
};

export default FeaturedClubCard;

// angular-migration/components/featured-club-card/featured-club-card.component.ts

import { Component, Input } from '@angular/core';
import { Club } from '../../models/club.model';

@Component({
  selector: 'app-featured-club-card',
  templateUrl: './featured-club-card.component.html',
  styleUrls: ['./featured-club-card.component.scss']
})
export class FeaturedClubCardComponent {
  @Input() club!: Club;
}


<div class="w-full border-0 overflow-hidden group transition-all duration-300 relative">
  <div *ngIf="club.image" class="w-full h-[300px] overflow-hidden relative">
    <div class="absolute inset-0 bg-gradient-to-t from-background to-transparent z-10"></div>
    <img [src]="club.image" [alt]="club.name" class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105">
    <div class="absolute bottom-0 left-0 right-0 p-6 z-20">
      <h2 class="text-2xl font-bold mb-2">{{club.name}}</h2>
      
      <div class="flex items-center gap-2 mb-3">
        <span class="inline-flex items-center rounded-md border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 bg-background/30 backdrop-blur-sm">
          <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-3 w-3 text-yellow-500 mr-1">
            <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
          </svg>
          {{club.rating}}
        </span>
        <span class="inline-flex items-center rounded-md border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 bg-background/30 backdrop-blur-sm">
          <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-3 w-3 mr-1">
            <circle cx="12" cy="12" r="10"></circle>
            <polyline points="12 6 12 12 16 14"></polyline>
          </svg>
          {{club.openingHours}}
        </span>
        <span *ngIf="club.activeParty" class="inline-flex items-center rounded-md border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 bg-party">
          <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-3 w-3 mr-1">
            <path d="M9 18V5l12-2v13"></path>
            <circle cx="6" cy="18" r="3"></circle>
            <circle cx="18" cy="16" r="3"></circle>
          </svg>
          Active Party
        </span>
      </div>
      
      <p class="text-sm text-muted-foreground mb-4 max-w-2xl line-clamp-2">
        {{club.description}}
      </p>
      
      <div class="space-y-2">
        <div>
          <h3 class="text-sm font-medium uppercase text-muted-foreground mb-1">
            Featured Artist
          </h3>
          <p class="text-lg">Artist</p>
        </div>
        
        <div>
          <h3 class="text-sm font-medium uppercase text-muted-foreground mb-1">
            Location
          </h3>
          <p class="text-sm flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4 mr-1">
              <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path>
              <circle cx="12" cy="10" r="3"></circle>
            </svg>
            {{club.address}}
          </p>
        </div>
        
        <div class="flex flex-wrap gap-1 mt-3">
          <span *ngFor="let genre of club.musicGenres" class="inline-flex items-center rounded-md border px-2.5 py-0.5 text-xs font-semibold bg-secondary text-secondary-foreground">
            {{genre}}
          </span>
        </div>
      </div>
      
      <button class="inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none bg-primary text-primary-foreground hover:bg-primary/90 h-10 py-2 px-4 mt-4 party-button">
        Learn More 
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4 ml-1">
          <path d="M5 12h14"></path>
          <path d="m12 5 7 7-7 7"></path>
        </svg>
      </button>
    </div>
  </div>
</div>
